function run_btn_tuberculosis(object,event,h)
%RUN_BTN_TUBERCULOSIS Summary of this function goes here
%   Detailed explanation goes here
 
listbox_layers = findobj_figure(h.figure,'Set Parameters','listbox');
layer = h.tuberculosis_layers(listbox_layers.Value);
    
h.tuberculosis_layers(listbox_layers.Value).result = codetuberculosesida(layer.pi1, layer.pi2, layer.pi3, ...
                                                                         layer.alpha, layer.beta,  layer.varepsilon, ...
                                                                         layer.muvih, layer.sigma, layer.theta1,     ...
                                                                         layer.theta2, layer.p, ...
                                                                         layer.muS, layer.muE, layer.omega, layer.muL,layer.nu, ...
                                                                         layer.muI, layer.tau , layer.A, layer.T, layer.S0, layer.V0, ...
                                                                         layer.Svih0,layer.E0, layer.L0, layer.I0 );


end

